from random import randint

MaleDogNames = ["Augustus",
                "Coy",
                "Trey",
                "Rex",
                "Leopoldo",
                "Jerald",
                "Tom",
                "Kristofer",
                "Fabian",
                "Freddy",
                "Roberto",
                "Noble",
                "Joesph",
                "Jess",
                "Jerrell",
                "Lino",
                "Stacey",
                "Quintin",
                "Homer",
                "Johnny",
                "Alexis",
                "Antoine",
                "Sebastian",
                "Lynwood",
                "Rudolph",
                "Carlo",
                "Frankie",
                "Logan",
                "Elmo",
                "Jules",
                "Jackie",
                "Jewel",
                "Louis",
                "Trent",
                "Alfred",
                "Rolf",
                "Robt",
                "Vincenzo",
                "Joe",
                "Sheldon",
                "Jerrod",
                "Foster",
                "Gene",
                "Heriberto",
                "Ira",
                "Enrique",
                "Norbert",
                "Carmelo",
                "Jeff",
                "Andre"]

FemaleDogNames = ["Marivel",
                  "Elinor",
                  "Assunta",
                  "Roxie",
                  "Veronique",
                  "Jeanne",
                  "Nell",
                  "Lashandra",
                  "Susy",
                  "Enid",
                  "Erica",
                  "Barbera",
                  "Anya",
                  "Maryalice",
                  "Robena",
                  "Alysha",
                  "Jacquie",
                  "Sherise",
                  "Carri",
                  "Marisa",
                  "Nerissa",
                  "Toni",
                  "Doreen",
                  "Melanie",
                  "Despina",
                  "Agueda",
                  "Madelyn",
                  "Tamisha",
                  "Jone",
                  "Anja",
                  "Rosa",
                  "Venita",
                  "Portia",
                  "Shaina",
                  "Kenisha",
                  "Mona",
                  "Rebecca",
                  "Keshia",
                  "Karleen",
                  "Zenobia",
                  "Melia",
                  "Clorinda",
                  "Deonna",
                  "Illa",
                  "Annelle",
                  "Rachael",
                  "Lizzette",
                  "Donella",
                  "Matha",
                  "Muoi",
                  ]

DogSpecies = ["Afghan Hound",
              "Airedale terrier",
              "Akita",
              "American Foxhound",
              "Amstaff",
              "Australian Cattle Dog",
              "Australian Shepherd",
              "Black and Tan",
              "Black Lab",
              "Border Collie",
              "Borzoi",
              "Boxer",
              "Brittany",
              "Bullmastiff",
              "Bull Terrier",
              "Chessie",
              "Canaan Dog",
              "Chow Chow",
              "Collie",
              "Curly Coat Retriever",
              "Dalmatian",
              "Doberman Pinscher",
              "English Foxhound",
              "German Shepherd",
              "German Shorthair",
              "Giant schnauzer",
              "Golden Retriever",
              "Goldendoodle",
              "Great Dane",
              "Greyhound",
              "Husky",
              "Irish Wolfhound",
              "Keeshound",
              "Kerry Blue Terrier",
              "Labradinger",
              "Labradoodle",
              "Mastiff",
              "Newfoundland",
              "Norsk Elk Shepherd",
              "Pit Bull Terrier",
              "Pointer",
              "Poodle",
              "Redbone Coonhound",
              "Rottweiler",
              "St. Bernard",
              "Saluki",
              "Samoyed",
              "Weimeraner",
              "Whippet",
              "Yellow Lab",
              "Basenji",
              "Beagle",
              "Black Russian Terrier",
              "Bocker",
              "Boston Terrier",
              "Cardigan Corgi",
              "Chihuahua",
              "English bulldog",
              "French bulldog",
              "Italian greyhound",
              "Jack Russell terrier",
              "Mini bull terrier",
              "Mini poodle",
              "Mini schnauzer",
              "Pembroke Welsh Corgi",
              "Pug",
              "Puggle",
              "Schipperke",
              "Schnoodle",
              "Shiba Inu",
              "Short fox terrier",
              "Spaniel",
              "Mini Staffordshire"]


def rand_male_name():
    return MaleDogNames[randint(0, len(MaleDogNames) - 1)]


def rand_female_name():
    return FemaleDogNames[randint(0, len(FemaleDogNames) - 1)]


def rand_gender():
    if randint(0, 1) == 0:
        return "Male"
    else:
        return "Female"


def rand_species():
    return DogSpecies[randint(0, len(DogSpecies) - 1)]
