from random import randint

MaleDogNames = ["Augustus",
                "Coy",
                "Trey",
                "Rex",
                "Leopoldo",
                "Jerald",
                "Tom",
                "Kristofer",
                "Fabian",
                "Freddy",
                "Roberto",
                "Noble",
                "Joesph",
                "Jess",
                "Jerrell",
                "Lino",
                "Stacey",
                "Quintin",
                "Homer",
                "Johnny",
                "Alexis",
                "Antoine",
                "Sebastian",
                "Lynwood",
                "Rudolph",
                "Carlo",
                "Frankie",
                "Logan",
                "Elmo",
                "Jules",
                "Jackie",
                "Jewel",
                "Louis",
                "Trent",
                "Alfred",
                "Rolf",
                "Robt",
                "Vincenzo",
                "Joe",
                "Sheldon",
                "Jerrod",
                "Foster",
                "Gene",
                "Heriberto",
                "Ira",
                "Enrique",
                "Norbert",
                "Carmelo",
                "Jeff",
                "Andre"]

FemaleDogNames = ["Marivel",
                  "Elinor",
                  "Assunta",
                  "Roxie",
                  "Veronique",
                  "Jeanne",
                  "Nell",
                  "Lashandra",
                  "Susy",
                  "Enid",
                  "Erica",
                  "Barbera",
                  "Anya",
                  "Maryalice",
                  "Robena",
                  "Alysha",
                  "Jacquie",
                  "Sherise",
                  "Carri",
                  "Marisa",
                  "Nerissa",
                  "Toni",
                  "Doreen",
                  "Melanie",
                  "Despina",
                  "Agueda",
                  "Madelyn",
                  "Tamisha",
                  "Jone",
                  "Anja",
                  "Rosa",
                  "Venita",
                  "Portia",
                  "Shaina",
                  "Kenisha",
                  "Mona",
                  "Rebecca",
                  "Keshia",
                  "Karleen",
                  "Zenobia",
                  "Melia",
                  "Clorinda",
                  "Deonna",
                  "Illa",
                  "Annelle",
                  "Rachael",
                  "Lizzette",
                  "Donella",
                  "Matha",
                  "Muoi",
                  ]

DogSpecies = ["Irish Wolfhound",
              "Golden Retriever",
              "German Shepherd",
              "Bulldog",
              "Beagle",
              "Poodle",
              "Bulldog",
              "Yorkshire Terrier",
              "Rottweiler",
              "Dachshund",
              "Chihuahua",
              "Pug",
              "Cocker Spaniel",
              "Siberian Husky",
              "Shih Tzu",
              "Pomeranian",
              "Great Dane",
              "Jack Russell Terrier",
              "Dalmation",
              "Saint Bernard"]


def rand_male_name():
    return MaleDogNames[randint(0, len(MaleDogNames) - 1)]


def rand_female_name():
    return FemaleDogNames[randint(0, len(FemaleDogNames) - 1)]


def rand_gender():
    if randint(0, 1) == 0:
        return 'Male'
    else:
        return 'Female'


def rand_species():
    return DogSpecies[randint(0, len(DogSpecies) - 1)]
